// Personal French word list — Dutch glosses.
// fr: the word or expression (nouns include their article, verbs in the infinitive)
// nl: Dutch meaning  |  pos: part of speech  |  cat: category
export const WORDS = [
  // --- Expressions & idioms ---
  { fr: "avoir la flemme", nl: "geen zin hebben, lui zijn", pos: "expr", cat: "Expressions" },
  { fr: "être à la bourre", nl: "te laat zijn, gehaast zijn", pos: "expr", cat: "Expressions" },
  { fr: "avoir la dalle", nl: "honger hebben", pos: "expr", cat: "Expressions" },
  { fr: "ça caille ici", nl: "het is hier ijskoud", pos: "expr", cat: "Expressions" },
  { fr: "c'est relou", nl: "dat is vervelend (verlan van 'lourd')", pos: "expr", cat: "Expressions" },
  { fr: "tu parles !", nl: "dat meen je niet!, ammehoela!", pos: "expr", cat: "Expressions" },
  { fr: "avoir hâte", nl: "ergens naar uitkijken", pos: "expr", cat: "Expressions" },
  { fr: "c'est blindé", nl: "het is er stampvol", pos: "expr", cat: "Expressions" },
  { fr: "ça me trotte dans la tête", nl: "dat blijft door mijn hoofd spelen", pos: "expr", cat: "Expressions" },
  { fr: "montrer patte blanche", nl: "zijn identiteit aantonen", pos: "expr", cat: "Expressions" },
  { fr: "à l'insu de", nl: "zonder medeweten van", pos: "expr", cat: "Expressions" },
  { fr: "agir en amont", nl: "preventief handelen", pos: "expr", cat: "Expressions" },
  { fr: "en vrac", nl: "los, in bulk; rommelig", pos: "expr", cat: "Expressions" },
  { fr: "à la louche", nl: "uit de losse pols, ruw geschat", pos: "expr", cat: "Expressions" },
  { fr: "le comble", nl: "het toppunt", pos: "n.m.", cat: "Expressions" },
  { fr: "un loupé", nl: "een misser", pos: "n.m.", cat: "Expressions" },
  { fr: "monter d'un cran", nl: "een tandje hoger gaan", pos: "expr", cat: "Expressions" },
  { fr: "tenir le haut du pavé", nl: "de bovenhand hebben", pos: "expr", cat: "Expressions" },
  { fr: "le coup est rude", nl: "de klap komt hard aan", pos: "expr", cat: "Expressions" },
  { fr: "caresser l'espoir", nl: "de hoop koesteren", pos: "expr", cat: "Expressions" },
  { fr: "ça ne fait pas le poids", nl: "niet opgewassen zijn tegen", pos: "expr", cat: "Expressions" },
  { fr: "se murer dans le silence", nl: "zich in stilzwijgen hullen", pos: "expr", cat: "Expressions" },
  { fr: "rentrer bredouille", nl: "met lege handen terugkeren", pos: "expr", cat: "Expressions" },
  { fr: "ça ne se trouve pas sous le sabot d'un cheval", nl: "dat ligt niet voor het oprapen", pos: "expr", cat: "Expressions" },

  // --- Emotions & attitudes ---
  { fr: "agacer", nl: "irriteren, ergeren", pos: "v", cat: "Emotions" },
  { fr: "être outré", nl: "verontwaardigd zijn", pos: "expr", cat: "Emotions" },
  { fr: "grincheux", nl: "chagrijnig, knorrig", pos: "adj", cat: "Emotions" },
  { fr: "la lassitude", nl: "vermoeidheid, moedeloosheid", pos: "n.f.", cat: "Emotions" },
  { fr: "sidérer", nl: "verbijsteren", pos: "v", cat: "Emotions" },
  { fr: "ruminer", nl: "piekeren, herkauwen", pos: "v", cat: "Emotions" },
  { fr: "se vanter", nl: "opscheppen", pos: "v", cat: "Emotions" },
  { fr: "narguer", nl: "tarten, beschimpen", pos: "v", cat: "Emotions" },
  { fr: "pavoiser", nl: "pronken, de vlag uithangen", pos: "v", cat: "Emotions" },
  { fr: "mettre en rogne", nl: "iemand woedend maken", pos: "expr", cat: "Emotions" },
  { fr: "les yeux hagards", nl: "een verwilderde blik", pos: "n.m.pl", cat: "Emotions" },

  // --- Actions & verbs ---
  { fr: "épingler", nl: "vastspelden; betrappen", pos: "v", cat: "Actions" },
  { fr: "éparpiller", nl: "verstrooien, verspreiden", pos: "v", cat: "Actions" },
  { fr: "s'engouffrer", nl: "naar binnen stormen", pos: "v", cat: "Actions" },
  { fr: "se ruer", nl: "zich haasten, stormen op", pos: "v", cat: "Actions" },
  { fr: "accourir", nl: "toesnellen", pos: "v", cat: "Actions" },
  { fr: "s'attarder", nl: "talmen, blijven hangen", pos: "v", cat: "Actions" },
  { fr: "hocher la tête", nl: "knikken", pos: "v", cat: "Actions" },
  { fr: "s'agenouiller", nl: "knielen", pos: "v", cat: "Actions" },
  { fr: "brandir", nl: "zwaaien met, hanteren", pos: "v", cat: "Actions" },
  { fr: "ôter", nl: "wegnemen, uittrekken", pos: "v", cat: "Actions" },
  { fr: "ballotter", nl: "heen en weer slingeren", pos: "v", cat: "Actions" },
  { fr: "galérer", nl: "ploeteren, afzien", pos: "v", cat: "Actions" },
  { fr: "agrémenter", nl: "opsmukken, verfraaien", pos: "v", cat: "Actions" },
  { fr: "s'embourber", nl: "vastlopen, verzanden", pos: "v", cat: "Actions" },
  { fr: "faillir", nl: "bijna doen (il a failli tomber)", pos: "v", cat: "Actions" },
  { fr: "subsister", nl: "blijven bestaan, overleven", pos: "v", cat: "Actions" },
  { fr: "furtif", nl: "stiekem, heimelijk", pos: "adj", cat: "Actions" },

  // --- Crime ---
  { fr: "le vol à l'étalage", nl: "winkeldiefstal", pos: "n.m.", cat: "Crime" },
  { fr: "le butin", nl: "de buit", pos: "n.m.", cat: "Crime" },
  { fr: "le repaire", nl: "schuilplaats, hol", pos: "n.m.", cat: "Crime" },
  { fr: "la cagoule", nl: "bivakmuts", pos: "n.f.", cat: "Crime" },
  { fr: "le receleur", nl: "de heler", pos: "n.m.", cat: "Crime" },
  { fr: "les choufs", nl: "uitkijkposten (bij drugshandel)", pos: "n.m.pl", cat: "Crime" },
  { fr: "le comparse", nl: "handlanger, medeplichtige", pos: "n.m.", cat: "Crime" },
  { fr: "la traque", nl: "klopjacht", pos: "n.f.", cat: "Crime" },
  { fr: "se tramer", nl: "in het geheim beraamd worden", pos: "v", cat: "Crime" },
  { fr: "quadriller", nl: "uitkammen, systematisch afzetten", pos: "v", cat: "Crime" },
  { fr: "pister", nl: "volgen, schaduwen", pos: "v", cat: "Crime" },
  { fr: "cerné", nl: "ingesloten, omsingeld", pos: "adj", cat: "Crime" },
  { fr: "confondre", nl: "ontmaskeren; verwarren", pos: "v", cat: "Crime" },
  { fr: "en éclaireur", nl: "op verkenning", pos: "expr", cat: "Crime" },
  { fr: "le guet-apens", nl: "hinderlaag", pos: "n.m.", cat: "Crime" },
  { fr: "une souricière", nl: "val, hinderlaag", pos: "n.f.", cat: "Crime" },
  { fr: "déguerpir", nl: "'m smeren, wegwezen", pos: "v", cat: "Crime" },
  { fr: "échapper de peu", nl: "ternauwernood ontsnappen", pos: "expr", cat: "Crime" },
  { fr: "l'engrenage", nl: "vicieuze cirkel, spiraal", pos: "n.m.", cat: "Crime" },
  { fr: "une effroyable dérive", nl: "een verschrikkelijke ontsporing", pos: "n.f.", cat: "Crime" },
  { fr: "la cagnotte", nl: "spaarpot, gemeenschappelijke pot", pos: "n.f.", cat: "Crime" },
  { fr: "le pactole", nl: "goudmijn, jackpot", pos: "n.m.", cat: "Crime" },
  { fr: "le lingot d'or", nl: "goudstaaf", pos: "n.m.", cat: "Crime" },
  { fr: "la maroquinerie de luxe", nl: "luxe lederwaren", pos: "n.f.", cat: "Crime" },
  { fr: "la porte blindée", nl: "gepantserde deur", pos: "n.f.", cat: "Crime" },
  { fr: "une masse", nl: "een moker", pos: "n.f.", cat: "Crime" },
  { fr: "le scaphandre", nl: "duikpak", pos: "n.m.", cat: "Crime" },
  { fr: "les pieds nickelés", nl: "prutsers, klungelaars", pos: "n.m.pl", cat: "Crime" },
  { fr: "l'étau se resserre", nl: "de bankschroef wordt aangedraaid", pos: "expr", cat: "Crime" },
  { fr: "dans le collimateur", nl: "in het vizier", pos: "expr", cat: "Crime" },

  // --- Justice ---
  { fr: "la comparution", nl: "verschijning voor de rechter", pos: "n.f.", cat: "Justice" },
  { fr: "écoper", nl: "incasseren, oplopen (een straf)", pos: "v", cat: "Justice" },
  { fr: "encourir", nl: "riskeren, oplopen", pos: "v", cat: "Justice" },
  { fr: "imputer", nl: "toeschrijven, aanrekenen", pos: "v", cat: "Justice" },
  { fr: "la résidence surveillée", nl: "huisarrest", pos: "n.f.", cat: "Justice" },
  { fr: "l'opprobre", nl: "smaad, schande", pos: "n.m.", cat: "Justice" },
  { fr: "l'apologie", nl: "verheerlijking", pos: "n.f.", cat: "Justice" },

  // --- Violence & weapons ---
  { fr: "un coup de semonce", nl: "waarschuwingsschot", pos: "n.m.", cat: "Violence" },
  { fr: "tirer à bout portant", nl: "van dichtbij neerschieten", pos: "expr", cat: "Violence" },
  { fr: "dégainer une arme", nl: "een wapen trekken", pos: "v", cat: "Violence" },
  { fr: "une douille", nl: "patroonhuls", pos: "n.f.", cat: "Violence" },
  { fr: "les rayures", nl: "groeven (in een geweerloop)", pos: "n.f.pl", cat: "Violence" },
  { fr: "le gaz lacrymogène", nl: "traangas", pos: "n.m.", cat: "Violence" },
  { fr: "le bouclier", nl: "schild", pos: "n.m.", cat: "Violence" },
  { fr: "un blindé à chenilles", nl: "rupspantservoertuig", pos: "n.m.", cat: "Violence" },
  { fr: "l'épée", nl: "het zwaard", pos: "n.f.", cat: "Violence" },
  { fr: "le bourreau", nl: "de beul", pos: "n.m.", cat: "Violence" },
  { fr: "l'artificier", nl: "pyrotechnicus, explosievenexpert", pos: "n.m.", cat: "Violence" },
  { fr: "les imprécations", nl: "verwensingen", pos: "n.f.pl", cat: "Violence" },
  { fr: "indemne", nl: "ongedeerd", pos: "adj", cat: "Violence" },
  { fr: "le vacarme", nl: "kabaal, herrie", pos: "n.m.", cat: "Violence" },

  // --- People ---
  { fr: "l'interlocutrice", nl: "gesprekspartner (vrouw)", pos: "n.f.", cat: "People" },
  { fr: "le forcené", nl: "dolgedraaide man, razende", pos: "n.m.", cat: "People" },
  { fr: "une andouille", nl: "domkop, sukkel", pos: "n.f.", cat: "People" },
  { fr: "un lascar", nl: "gozer, snuiter", pos: "n.m.", cat: "People" },
  { fr: "chevronné", nl: "doorgewinterd, ervaren", pos: "adj", cat: "People" },
  { fr: "un baroudeur", nl: "globetrotter, avonturier", pos: "n.m.", cat: "People" },
  { fr: "la calvitie", nl: "kaalheid", pos: "n.f.", cat: "People" },

  // --- Society & news ---
  { fr: "une communauté bienveillante", nl: "een welwillende, respectvolle gemeenschap", pos: "n.f.", cat: "Society" },
  { fr: "revendiquer", nl: "opeisen, claimen", pos: "v", cat: "Society" },
  { fr: "l'ingérence", nl: "inmenging, tussenkomst", pos: "n.f.", cat: "Society" },
  { fr: "préoccupant", nl: "zorgwekkend", pos: "adj", cat: "Society" },
  { fr: "répandu", nl: "wijdverbreid", pos: "adj", cat: "Society" },
  { fr: "encombrant", nl: "omvangrijk, hinderlijk", pos: "adj", cat: "Society" },
  { fr: "mouvementé", nl: "hectisch, bewogen", pos: "adj", cat: "Society" },

  // --- Faith & death ---
  { fr: "le péché", nl: "de zonde", pos: "n.m.", cat: "Faith" },
  { fr: "prêcher", nl: "prediken", pos: "v", cat: "Faith" },
  { fr: "le mécréant", nl: "ongelovige", pos: "n.m.", cat: "Faith" },
  { fr: "le prosélytisme", nl: "bekeringsijver", pos: "n.m.", cat: "Faith" },
  { fr: "les obsèques", nl: "de uitvaart, begrafenis", pos: "n.f.pl", cat: "Faith" },

  // --- Work & study ---
  { fr: "l'entretien d'embauche", nl: "sollicitatiegesprek", pos: "n.m.", cat: "Work" },
  { fr: "prendre du galon", nl: "promotie maken", pos: "expr", cat: "Work" },
  { fr: "recalé", nl: "gebuisd, gezakt", pos: "adj", cat: "Work" },
  { fr: "le manutentionnaire", nl: "magazijnier", pos: "n.m.", cat: "Work" },
  { fr: "le domaine de prédilection", nl: "voorkeursgebied, specialiteit", pos: "n.m.", cat: "Work" },
  { fr: "le concessionnaire", nl: "dealer, officiële handelaar", pos: "n.m.", cat: "Work" },

  // --- Language & reading ---
  { fr: "la maxime", nl: "spreuk, zinspreuk", pos: "n.f.", cat: "Language" },
  { fr: "la tournure", nl: "formulering, wending", pos: "n.f.", cat: "Language" },
  { fr: "décortiquer", nl: "ontleden, uitpluizen", pos: "v", cat: "Language" },
  { fr: "un tuyau miracle", nl: "een wondertip", pos: "n.m.", cat: "Language" },
  { fr: "l'astuce", nl: "truc, handige tip", pos: "n.f.", cat: "Language" },
  { fr: "le fascicule", nl: "brochure, katern", pos: "n.m.", cat: "Language" },
  { fr: "le polar", nl: "misdaadroman, thriller", pos: "n.m.", cat: "Language" },

  // --- Food & drink ---
  { fr: "le poivron", nl: "paprika", pos: "n.m.", cat: "Food" },
  { fr: "la date de péremption", nl: "houdbaarheidsdatum", pos: "n.f.", cat: "Food" },
  { fr: "comestible", nl: "eetbaar", pos: "adj", cat: "Food" },
  { fr: "un en-cas", nl: "snack, tussendoortje", pos: "n.m.", cat: "Food" },
  { fr: "grignoter", nl: "knabbelen", pos: "v", cat: "Food" },
  { fr: "la galette", nl: "hartige (boekweit)pannenkoek", pos: "n.f.", cat: "Food" },
  { fr: "gourmand", nl: "gulzig; lekkerbek", pos: "adj", cat: "Food" },
  { fr: "une cafetière à piston", nl: "cafetière, French press", pos: "n.f.", cat: "Food" },
  { fr: "trinquer", nl: "proosten, klinken", pos: "v", cat: "Food" },

  // --- Home & objects ---
  { fr: "un coussin moelleux", nl: "een zacht kussen", pos: "n.m.", cat: "Home" },
  { fr: "mou", nl: "slap, zacht", pos: "adj", cat: "Home" },
  { fr: "l'anse", nl: "het oor (van een kop, mand of tas)", pos: "n.f.", cat: "Home" },
  { fr: "à rayures", nl: "gestreept", pos: "adj", cat: "Home" },
  { fr: "l'argile", nl: "klei", pos: "n.f.", cat: "Home" },
  { fr: "une borne", nl: "zuil, terminal, paal", pos: "n.f.", cat: "Home" },
  { fr: "fripé", nl: "verkreukeld", pos: "adj", cat: "Home" },

  // --- Nature & science ---
  { fr: "le poulailler", nl: "kippenhok", pos: "n.m.", cat: "Nature" },
  { fr: "se désagréger", nl: "uiteenvallen, afbrokkelen", pos: "v", cat: "Nature" },
  { fr: "l'énergie éolienne", nl: "windenergie", pos: "n.f.", cat: "Nature" },
];
