// Personal French word list — Dutch glosses.
// fr: the word or expression (nouns include their article, verbs in the infinitive)
// nl: Dutch meaning  |  pos: part of speech  |  cat: category  |  added: date added (YYYY-MM-DD)
export const WORDS = [
  // --- Expressions & idioms ---
  { fr: "avoir la flemme", nl: "geen zin hebben, lui zijn", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "être à la bourre", nl: "te laat zijn, gehaast zijn", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "avoir la dalle", nl: "honger hebben", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "ça caille ici", nl: "het is hier ijskoud", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "c'est relou", nl: "dat is vervelend (verlan van 'lourd')", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "tu parles !", nl: "dat meen je niet!, ammehoela!", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "avoir hâte", nl: "ergens naar uitkijken", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "c'est blindé", nl: "het is er stampvol", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "ça me trotte dans la tête", nl: "dat blijft door mijn hoofd spelen", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "montrer patte blanche", nl: "zijn identiteit aantonen", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "à l'insu de", nl: "zonder medeweten van", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "agir en amont", nl: "preventief handelen", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "en vrac", nl: "los, in bulk; rommelig", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "à la louche", nl: "uit de losse pols, ruw geschat", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "le comble", nl: "het toppunt", pos: "n.m.", cat: "Expressions", added: "2026-08-03" },
  { fr: "un loupé", nl: "een misser", pos: "n.m.", cat: "Expressions", added: "2026-08-03" },
  { fr: "monter d'un cran", nl: "een tandje hoger gaan", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "tenir le haut du pavé", nl: "de bovenhand hebben", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "le coup est rude", nl: "de klap komt hard aan", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "caresser l'espoir", nl: "de hoop koesteren", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "ça ne fait pas le poids", nl: "niet opgewassen zijn tegen", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "se murer dans le silence", nl: "zich in stilzwijgen hullen", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "rentrer bredouille", nl: "met lege handen terugkeren", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "ça ne se trouve pas sous le sabot d'un cheval", nl: "dat ligt niet voor het oprapen", pos: "expr", cat: "Expressions", added: "2026-08-03" },
  { fr: "à jeun", nl: "nuchter", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "battre son plein", nl: "in volle gang zijn", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "en terrain conquis", nl: "op vertrouwd terrein", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "sans crier gare", nl: "zonder enige waarschuwing", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "en trombe", nl: "bliksemsnel, in volle vaart", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "noyer le poisson", nl: "om de hete brij heen draaien", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "sans ménagement", nl: "zonder pardon, onzacht", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "être rompu à", nl: "ergens aan gewend/bedreven zijn", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "enfoncer le clou", nl: "een punt nog eens extra benadrukken", pos: "expr", cat: "Expressions", added: "2026-08-29" },
  { fr: "sans sourciller", nl: "zonder te knipperen (met de ogen)", pos: "expr", cat: "Expressions", added: "2026-09-11" },
  { fr: "en guise de", nl: "bij wijze van", pos: "expr", cat: "Expressions", added: "2026-09-11" },
  { fr: "truffé de", nl: "doorspekt van, krioelend van", pos: "expr", cat: "Expressions", added: "2026-09-11" },
  { fr: "avoir le cran", nl: "het lef hebben", pos: "expr", cat: "Expressions", added: "2026-09-11" },
  { fr: "monter au créneau", nl: "in de bres springen", pos: "expr", cat: "Expressions", added: "2026-09-11" },
  { fr: "se gourer", nl: "zich vergissen", pos: "v", cat: "Expressions", added: "2026-09-11" },
  { fr: "gai comme un pinson", nl: "vrolijk als een vink", pos: "expr", cat: "Expressions", added: "2026-09-16" },
  { fr: "courir sur le haricot", nl: "op de zenuwen werken", pos: "expr", cat: "Expressions", added: "2026-09-16" },
  { fr: "jurer comme un charretier", nl: "vloeken als een ketter", pos: "expr", cat: "Expressions", added: "2026-09-16" },
  { fr: "appeler à la rescousse", nl: "om versterking vragen", pos: "expr", cat: "Expressions", added: "2026-09-16" },
  { fr: "je m'incline", nl: "ik geef me gewonnen", pos: "expr", cat: "Expressions", added: "2026-09-16" },
  { fr: "quel gâchis", nl: "wat een verspilling", pos: "expr", cat: "Expressions", added: "2026-09-16" },
  { fr: "c'est aléatoire", nl: "overgeleverd aan het toeval", pos: "expr", cat: "Expressions", added: "2026-09-16" },
  { fr: "elle se volatilise", nl: "ze gaat in rook op", pos: "expr", cat: "Expressions", added: "2026-09-16" },

  { fr: "ne pas avoir la côte", nl: "niet populair zijn", pos: "expr", cat: "Expressions", added: "2026-09-27" },
  { fr: "se dépatouiller", nl: "zich redden, zich eruit werken", pos: "v", cat: "Expressions", added: "2026-09-27" },
  { fr: "faire la fine bouche", nl: "kieskeurig zijn, zijn neus optrekken", pos: "expr", cat: "Expressions", added: "2026-09-27" },
  { fr: "éviter de gratter le vernis", nl: "de schijn hooghouden, niet te diep graven", pos: "expr", cat: "Expressions", added: "2026-09-27" },
  { fr: "mettre la puce à l'oreille", nl: "iemand aan het denken zetten, achterdochtig maken", pos: "expr", cat: "Expressions", added: "2026-09-27" },
  { fr: "bon pour l'émulation", nl: "goed voor gezonde rivaliteit", pos: "expr", cat: "Expressions", added: "2026-09-27" },
  { fr: "avoir un flair d'enfer", nl: "er een neus voor hebben", pos: "expr", cat: "Expressions", added: "2026-09-27" },
  { fr: "d'emblée", nl: "meteen, onmiddellijk", pos: "expr", cat: "Expressions", added: "2026-09-27" },
  { fr: "sur les chapeaux de roues", nl: "met gierende banden, op volle snelheid", pos: "expr", cat: "Expressions", added: "2026-09-29" },
  { fr: "faire chou blanc", nl: "niets opleveren, bot vangen", pos: "expr", cat: "Expressions", added: "2026-09-29" },
  { fr: "le dernier cri", nl: "de laatste trend", pos: "expr", cat: "Expressions", added: "2026-09-29" },
  { fr: "à 14h pétantes", nl: "klokslag 14 uur", pos: "expr", cat: "Expressions", added: "2026-09-29" },
  { fr: "un échange de bons procédés", nl: "elkaar een wederdienst bewijzen", pos: "expr", cat: "Expressions", added: "2026-09-29" },
  // --- Emotions & attitudes ---
  { fr: "agacer", nl: "irriteren, ergeren", pos: "v", cat: "Emotions", added: "2026-08-03" },
  { fr: "être outré", nl: "verontwaardigd zijn", pos: "expr", cat: "Emotions", added: "2026-08-03" },
  { fr: "grincheux", nl: "chagrijnig, knorrig", pos: "adj", cat: "Emotions", added: "2026-08-03" },
  { fr: "la lassitude", nl: "vermoeidheid, moedeloosheid", pos: "n.f.", cat: "Emotions", added: "2026-08-03" },
  { fr: "sidérer", nl: "verbijsteren", pos: "v", cat: "Emotions", added: "2026-08-03" },
  { fr: "ruminer", nl: "piekeren, herkauwen", pos: "v", cat: "Emotions", added: "2026-08-03" },
  { fr: "se vanter", nl: "opscheppen", pos: "v", cat: "Emotions", added: "2026-08-03" },
  { fr: "narguer", nl: "tarten, beschimpen", pos: "v", cat: "Emotions", added: "2026-08-03" },
  { fr: "pavoiser", nl: "pronken, de vlag uithangen", pos: "v", cat: "Emotions", added: "2026-08-03" },
  { fr: "mettre en rogne", nl: "iemand woedend maken", pos: "expr", cat: "Emotions", added: "2026-08-03" },
  { fr: "les yeux hagards", nl: "een verwilderde blik", pos: "n.m.pl", cat: "Emotions", added: "2026-08-03" },
  { fr: "l'avidité", nl: "hebzucht", pos: "n.f.", cat: "Emotions", added: "2026-08-29" },
  { fr: "flemmard", nl: "lui, een luiaard", pos: "adj", cat: "Emotions", added: "2026-08-29" },
  { fr: "chiffonner", nl: "dwars zitten, hinderen (ça me chiffonne)", pos: "v", cat: "Emotions", added: "2026-08-29" },
  { fr: "affolé", nl: "overstuur, in paniek", pos: "adj", cat: "Emotions", added: "2026-08-29" },
  { fr: "figé", nl: "verstijfd", pos: "adj", cat: "Emotions", added: "2026-08-29" },
  { fr: "démuni", nl: "machteloos, berooid", pos: "adj", cat: "Emotions", added: "2026-08-29" },
  { fr: "grogner", nl: "mopperen, grommen", pos: "v", cat: "Emotions", added: "2026-09-11" },
  { fr: "accablant", nl: "verpletterend, overweldigend", pos: "adj", cat: "Emotions", added: "2026-09-11" },
  { fr: "se dégonfler", nl: "terugkrabbelen", pos: "v", cat: "Emotions", added: "2026-09-11" },
  { fr: "le désarroi", nl: "verslagenheid, radeloosheid", pos: "n.m.", cat: "Emotions", added: "2026-09-11" },
  { fr: "affoler", nl: "panikeren, in paniek brengen", pos: "v", cat: "Emotions", added: "2026-09-16" },

  { fr: "abasourdi", nl: "verbijsterd", pos: "adj", cat: "Emotions", added: "2026-09-27" },
  { fr: "la récrimination", nl: "verwijt, beschuldiging", pos: "n.f.", cat: "Emotions", added: "2026-09-27" },
  { fr: "taquiner", nl: "plagen", pos: "v", cat: "Emotions", added: "2026-09-27" },
  { fr: "convoiter", nl: "begeren", pos: "v", cat: "Emotions", added: "2026-09-27" },
  { fr: "être échaudé(e)", nl: "het geleerd hebben (door schade en schande)", pos: "expr", cat: "Emotions", added: "2026-09-29" },
  { fr: "virulent", nl: "heftig", pos: "adj", cat: "Emotions", added: "2026-09-29" },
  { fr: "la convoitise", nl: "de begeerte", pos: "n.f.", cat: "Emotions", added: "2026-09-29" },
  // --- Actions & verbs ---
  { fr: "épingler", nl: "vastspelden; betrappen", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "éparpiller", nl: "verstrooien, verspreiden", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "s'engouffrer", nl: "naar binnen stormen", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "se ruer", nl: "zich haasten, stormen op", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "accourir", nl: "toesnellen", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "s'attarder", nl: "talmen, blijven hangen", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "hocher la tête", nl: "knikken", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "s'agenouiller", nl: "knielen", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "brandir", nl: "zwaaien met, hanteren", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "ôter", nl: "wegnemen, uittrekken", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "ballotter", nl: "heen en weer slingeren", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "galérer", nl: "ploeteren, afzien", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "agrémenter", nl: "opsmukken, verfraaien", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "s'embourber", nl: "vastlopen, verzanden", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "faillir", nl: "bijna doen (il a failli tomber)", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "subsister", nl: "blijven bestaan, overleven", pos: "v", cat: "Actions", added: "2026-08-03" },
  { fr: "furtif", nl: "stiekem, heimelijk", pos: "adj", cat: "Actions", added: "2026-08-03" },
  { fr: "morceler", nl: "opdelen, versnipperen", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "fredonner", nl: "neuriën", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "mater", nl: "kijken; in toom houden", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "puiser", nl: "putten, ontlenen", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "peaufiner", nl: "verfijnen, polijsten", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "vriller", nl: "ronddraaien, tollen", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "s'empresser", nl: "zich haasten", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "charbonner", nl: "hard werken, ploeteren", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "balayer", nl: "wegvegen", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "ébaucher", nl: "schetsen, ontwerpen", pos: "v", cat: "Actions", added: "2026-08-29" },
  { fr: "accroupi", nl: "gehurkt", pos: "adj", cat: "Actions", added: "2026-08-29" },
  { fr: "affûter", nl: "scherpen, slijpen", pos: "v", cat: "Actions", added: "2026-09-11" },
  { fr: "ébranler", nl: "doen wankelen", pos: "v", cat: "Actions", added: "2026-09-11" },
  { fr: "en titubant", nl: "wankelend", pos: "expr", cat: "Actions", added: "2026-09-11" },
  { fr: "lésiner", nl: "beknibbelen", pos: "v", cat: "Actions", added: "2026-09-16" },
  { fr: "s'avérer", nl: "blijken (te zijn)", pos: "v", cat: "Actions", added: "2026-09-16" },

  { fr: "dévisager", nl: "aanstaren", pos: "v", cat: "Actions", added: "2026-09-27" },
  { fr: "glandouiller", nl: "rondhangen, niksen", pos: "v", cat: "Actions", added: "2026-09-29" },
  { fr: "s'envenimer", nl: "verergeren, uit de hand lopen", pos: "v", cat: "Actions", added: "2026-09-29" },
  // --- Crime ---
  { fr: "le vol à l'étalage", nl: "winkeldiefstal", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "le butin", nl: "de buit", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "le repaire", nl: "schuilplaats, hol", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "la cagoule", nl: "bivakmuts", pos: "n.f.", cat: "Crime", added: "2026-08-03" },
  { fr: "le receleur", nl: "de heler", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "les choufs", nl: "uitkijkposten (bij drugshandel)", pos: "n.m.pl", cat: "Crime", added: "2026-08-03" },
  { fr: "le comparse", nl: "handlanger, medeplichtige", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "la traque", nl: "klopjacht", pos: "n.f.", cat: "Crime", added: "2026-08-03" },
  { fr: "se tramer", nl: "in het geheim beraamd worden", pos: "v", cat: "Crime", added: "2026-08-03" },
  { fr: "quadriller", nl: "uitkammen, systematisch afzetten", pos: "v", cat: "Crime", added: "2026-08-03" },
  { fr: "pister", nl: "volgen, schaduwen", pos: "v", cat: "Crime", added: "2026-08-03" },
  { fr: "cerné", nl: "ingesloten, omsingeld", pos: "adj", cat: "Crime", added: "2026-08-03" },
  { fr: "confondre", nl: "ontmaskeren; verwarren", pos: "v", cat: "Crime", added: "2026-08-03" },
  { fr: "en éclaireur", nl: "op verkenning", pos: "expr", cat: "Crime", added: "2026-08-03" },
  { fr: "le guet-apens", nl: "hinderlaag", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "une souricière", nl: "val, hinderlaag", pos: "n.f.", cat: "Crime", added: "2026-08-03" },
  { fr: "déguerpir", nl: "'m smeren, wegwezen", pos: "v", cat: "Crime", added: "2026-08-03" },
  { fr: "échapper de peu", nl: "ternauwernood ontsnappen", pos: "expr", cat: "Crime", added: "2026-08-03" },
  { fr: "l'engrenage", nl: "vicieuze cirkel, spiraal", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "une effroyable dérive", nl: "een verschrikkelijke ontsporing", pos: "n.f.", cat: "Crime", added: "2026-08-03" },
  { fr: "la cagnotte", nl: "spaarpot, gemeenschappelijke pot", pos: "n.f.", cat: "Crime", added: "2026-08-03" },
  { fr: "le pactole", nl: "goudmijn, jackpot", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "le lingot d'or", nl: "goudstaaf", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "la maroquinerie de luxe", nl: "luxe lederwaren", pos: "n.f.", cat: "Crime", added: "2026-08-03" },
  { fr: "la porte blindée", nl: "gepantserde deur", pos: "n.f.", cat: "Crime", added: "2026-08-03" },
  { fr: "une masse", nl: "een moker", pos: "n.f.", cat: "Crime", added: "2026-08-03" },
  { fr: "le scaphandre", nl: "duikpak", pos: "n.m.", cat: "Crime", added: "2026-08-03" },
  { fr: "les pieds nickelés", nl: "prutsers, klungelaars", pos: "n.m.pl", cat: "Crime", added: "2026-08-03" },
  { fr: "l'étau se resserre", nl: "de bankschroef wordt aangedraaid", pos: "expr", cat: "Crime", added: "2026-08-03" },
  { fr: "dans le collimateur", nl: "in het vizier", pos: "expr", cat: "Crime", added: "2026-08-03" },
  { fr: "les méfaits", nl: "misdaden, wandaden", pos: "n.m.pl", cat: "Crime", added: "2026-08-29" },
  { fr: "en cavale", nl: "op de vlucht", pos: "expr", cat: "Crime", added: "2026-08-29" },
  { fr: "en faction", nl: "op wacht, in dienst", pos: "expr", cat: "Crime", added: "2026-08-29" },
  { fr: "le vigile", nl: "bewaker", pos: "n.m.", cat: "Crime", added: "2026-09-11" },
  { fr: "passer au crible", nl: "onder de loep nemen", pos: "expr", cat: "Crime", added: "2026-09-11" },
  { fr: "s'esquiver", nl: "zich er tussenuit knijpen", pos: "v", cat: "Crime", added: "2026-09-11" },
  { fr: "la pioche", nl: "pikhouweel", pos: "n.f.", cat: "Crime", added: "2026-09-11" },
  { fr: "sillonner les alentours", nl: "de omgeving verkennen", pos: "expr", cat: "Crime", added: "2026-09-11" },
  { fr: "le ratissage", nl: "uitkammen (van een gebied)", pos: "n.m.", cat: "Crime", added: "2026-09-11" },
  { fr: "bâillonner", nl: "knevelen", pos: "v", cat: "Crime", added: "2026-09-11" },

  { fr: "le dépistage", nl: "opsporing", pos: "n.m.", cat: "Crime", added: "2026-09-27" },
  { fr: "le rebondissement", nl: "plot twist, onverwachte wending", pos: "n.m.", cat: "Crime", added: "2026-09-27" },
  { fr: "des liasses de billets", nl: "bundels bankbiljetten", pos: "n.f.pl", cat: "Crime", added: "2026-09-27" },
  { fr: "détrousser", nl: "beroven", pos: "v", cat: "Crime", added: "2026-09-27" },
  { fr: "dévaliser", nl: "plunderen, leegroven", pos: "v", cat: "Crime", added: "2026-09-29" },
  { fr: "confondre le suspect", nl: "de verdachte ontmaskeren", pos: "expr", cat: "Crime", added: "2026-09-29" },
  { fr: "prendre les paluches", nl: "vingerafdrukken nemen", pos: "expr", cat: "Crime", added: "2026-09-29" },
  { fr: "l'usurpation d'identité", nl: "identiteitsdiefstal", pos: "n.f.", cat: "Crime", added: "2026-09-29" },
  { fr: "mettre hors d'état de nuire", nl: "onschadelijk maken, inrekenen", pos: "expr", cat: "Crime", added: "2026-09-29" },
  { fr: "une opération coup de poing", nl: "bliksemactie", pos: "n.f.", cat: "Crime", added: "2026-09-29" },
  { fr: "le proxénétisme", nl: "seksuele uitbuiting, souteneurschap", pos: "n.m.", cat: "Crime", added: "2026-09-29" },
  { fr: "le racolage", nl: "tippelen", pos: "n.m.", cat: "Crime", added: "2026-09-29" },
  { fr: "le vendeur à la sauvette", nl: "illegale straatverkoper", pos: "n.m.", cat: "Crime", added: "2026-09-29" },
  // --- Justice ---
  { fr: "la comparution", nl: "verschijning voor de rechter", pos: "n.f.", cat: "Justice", added: "2026-08-03" },
  { fr: "écoper", nl: "incasseren, oplopen (een straf)", pos: "v", cat: "Justice", added: "2026-08-03" },
  { fr: "encourir", nl: "riskeren, oplopen", pos: "v", cat: "Justice", added: "2026-08-03" },
  { fr: "imputer", nl: "toeschrijven, aanrekenen", pos: "v", cat: "Justice", added: "2026-08-03" },
  { fr: "la résidence surveillée", nl: "huisarrest", pos: "n.f.", cat: "Justice", added: "2026-08-03" },
  { fr: "l'opprobre", nl: "smaad, schande", pos: "n.m.", cat: "Justice", added: "2026-08-03" },
  { fr: "l'apologie", nl: "verheerlijking", pos: "n.f.", cat: "Justice", added: "2026-08-03" },
  { fr: "l'attentat à la pudeur", nl: "aanranding van de eerbaarheid", pos: "n.m.", cat: "Justice", added: "2026-09-16" },

  { fr: "la déchéance", nl: "verval; verbeurdverklaring", pos: "n.f.", cat: "Justice", added: "2026-09-27" },
  { fr: "un délit passible d'une amende", nl: "een misdrijf waarop een boete staat", pos: "expr", cat: "Justice", added: "2026-09-29" },
  { fr: "le tapage nocturne", nl: "nachtlawaai", pos: "n.m.", cat: "Justice", added: "2026-09-29" },
  // --- Violence & weapons ---
  { fr: "un coup de semonce", nl: "waarschuwingsschot", pos: "n.m.", cat: "Violence", added: "2026-08-03" },
  { fr: "tirer à bout portant", nl: "van dichtbij neerschieten", pos: "expr", cat: "Violence", added: "2026-08-03" },
  { fr: "dégainer une arme", nl: "een wapen trekken", pos: "v", cat: "Violence", added: "2026-08-03" },
  { fr: "une douille", nl: "patroonhuls", pos: "n.f.", cat: "Violence", added: "2026-08-03" },
  { fr: "les rayures", nl: "groeven (in een geweerloop)", pos: "n.f.pl", cat: "Violence", added: "2026-08-03" },
  { fr: "le gaz lacrymogène", nl: "traangas", pos: "n.m.", cat: "Violence", added: "2026-08-03" },
  { fr: "le bouclier", nl: "schild", pos: "n.m.", cat: "Violence", added: "2026-08-03" },
  { fr: "un blindé à chenilles", nl: "rupspantservoertuig", pos: "n.m.", cat: "Violence", added: "2026-08-03" },
  { fr: "l'épée", nl: "het zwaard", pos: "n.f.", cat: "Violence", added: "2026-08-03" },
  { fr: "le bourreau", nl: "de beul", pos: "n.m.", cat: "Violence", added: "2026-08-03" },
  { fr: "l'artificier", nl: "pyrotechnicus, explosievenexpert", pos: "n.m.", cat: "Violence", added: "2026-08-03" },
  { fr: "les imprécations", nl: "verwensingen", pos: "n.f.pl", cat: "Violence", added: "2026-08-03" },
  { fr: "indemne", nl: "ongedeerd", pos: "adj", cat: "Violence", added: "2026-08-03" },
  { fr: "le vacarme", nl: "kabaal, herrie", pos: "n.m.", cat: "Violence", added: "2026-08-03" },
  { fr: "le collimateur", nl: "vizier (optisch richtmiddel)", pos: "n.m.", cat: "Violence", added: "2026-08-29" },
  { fr: "avoir la gâchette facile", nl: "snel geneigd zijn om te schieten", pos: "expr", cat: "Violence", added: "2026-09-11" },
  { fr: "se tabasser", nl: "elkaar in elkaar slaan", pos: "v", cat: "Violence", added: "2026-09-11" },
  { fr: "assiéger", nl: "belegeren", pos: "v", cat: "Violence", added: "2026-09-11" },
  { fr: "se faire laminer", nl: "een pak rammel krijgen", pos: "expr", cat: "Violence", added: "2026-09-11" },

  { fr: "l'arme blanche", nl: "steekwapen (niet-vuurwapen)", pos: "n.f.", cat: "Violence", added: "2026-09-27" },
  { fr: "une rixe", nl: "vechtpartij, opstootje", pos: "n.f.", cat: "Violence", added: "2026-09-27" },
  { fr: "plaqué au sol", nl: "tegen de grond gewerkt", pos: "expr", cat: "Violence", added: "2026-09-29" },
  // --- People ---
  { fr: "l'interlocutrice", nl: "gesprekspartner (vrouw)", pos: "n.f.", cat: "People", added: "2026-08-03" },
  { fr: "le forcené", nl: "dolgedraaide man, razende", pos: "n.m.", cat: "People", added: "2026-08-03" },
  { fr: "une andouille", nl: "domkop, sukkel", pos: "n.f.", cat: "People", added: "2026-08-03" },
  { fr: "un lascar", nl: "gozer, snuiter", pos: "n.m.", cat: "People", added: "2026-08-03" },
  { fr: "chevronné", nl: "doorgewinterd, ervaren", pos: "adj", cat: "People", added: "2026-08-03" },
  { fr: "un baroudeur", nl: "globetrotter, avonturier", pos: "n.m.", cat: "People", added: "2026-08-03" },
  { fr: "la calvitie", nl: "kaalheid", pos: "n.f.", cat: "People", added: "2026-08-03" },
  { fr: "espiègle", nl: "ondeugend, schalks", pos: "adj", cat: "People", added: "2026-08-29" },
  { fr: "désœuvré", nl: "werkloos, ledig, niets omhanden", pos: "adj", cat: "People", added: "2026-08-29" },
  { fr: "rablé", nl: "klein, gedrongen", pos: "adj", cat: "People", added: "2026-09-11" },
  { fr: "austère", nl: "streng, sober", pos: "adj", cat: "People", added: "2026-09-11" },
  { fr: "la clavicule", nl: "sleutelbeen", pos: "n.f.", cat: "People", added: "2026-09-11" },
  { fr: "le discernement", nl: "inzicht", pos: "n.m.", cat: "People", added: "2026-09-11" },
  { fr: "le frangin", nl: "broertje, broer (spreektaal)", pos: "n.m.", cat: "People", added: "2026-09-16" },
  { fr: "une péronnelle", nl: "leeghoofdig, kwebbelend vrouwmens", pos: "n.f.", cat: "People", added: "2026-09-16" },
  { fr: "mesquin", nl: "kleinzielig", pos: "adj", cat: "People", added: "2026-09-16" },
  { fr: "de cet acabit", nl: "van dat allooi, dat soort (mens)", pos: "expr", cat: "People", added: "2026-09-16" },

  { fr: "ventripotent", nl: "dikbuikig", pos: "adj", cat: "People", added: "2026-09-27" },
  { fr: "la fraise", nl: "hoofd, smoel (spreektaal)", pos: "n.f.", cat: "People", added: "2026-09-27" },
  { fr: "la convalescence", nl: "herstel(periode)", pos: "n.f.", cat: "People", added: "2026-09-27" },
  // --- Society & news ---
  { fr: "une communauté bienveillante", nl: "een welwillende, respectvolle gemeenschap", pos: "n.f.", cat: "Society", added: "2026-08-03" },
  { fr: "revendiquer", nl: "opeisen, claimen", pos: "v", cat: "Society", added: "2026-08-03" },
  { fr: "l'ingérence", nl: "inmenging, tussenkomst", pos: "n.f.", cat: "Society", added: "2026-08-03" },
  { fr: "préoccupant", nl: "zorgwekkend", pos: "adj", cat: "Society", added: "2026-08-03" },
  { fr: "répandu", nl: "wijdverbreid", pos: "adj", cat: "Society", added: "2026-08-03" },
  { fr: "encombrant", nl: "omvangrijk, hinderlijk", pos: "adj", cat: "Society", added: "2026-08-03" },
  { fr: "mouvementé", nl: "hectisch, bewogen", pos: "adj", cat: "Society", added: "2026-08-03" },
  { fr: "une asbl", nl: "vzw (association sans but lucratif)", pos: "n.f.", cat: "Society", added: "2026-08-29" },
  { fr: "fastidieux", nl: "vervelend, saai", pos: "adj", cat: "Society", added: "2026-08-29" },
  { fr: "la gabegie", nl: "wanbeheer", pos: "n.f.", cat: "Society", added: "2026-09-11" },
  { fr: "la cohue", nl: "gedrang, gewoel", pos: "n.f.", cat: "Society", added: "2026-09-16" },

  { fr: "les désagréments", nl: "ongemakken", pos: "n.m.pl", cat: "Society", added: "2026-09-27" },
  { fr: "une embarcation de fortune", nl: "een noodbootje, geïmproviseerd vaartuig", pos: "n.f.", cat: "Society", added: "2026-09-27" },
  { fr: "l'incivilité", nl: "overlast, asociaal gedrag", pos: "n.f.", cat: "Society", added: "2026-09-27" },
  { fr: "une population aisée", nl: "een welgestelde bevolking", pos: "expr", cat: "Society", added: "2026-09-29" },
  // --- Faith & death ---
  { fr: "le péché", nl: "de zonde", pos: "n.m.", cat: "Faith", added: "2026-08-03" },
  { fr: "prêcher", nl: "prediken", pos: "v", cat: "Faith", added: "2026-08-03" },
  { fr: "le mécréant", nl: "ongelovige", pos: "n.m.", cat: "Faith", added: "2026-08-03" },
  { fr: "le prosélytisme", nl: "bekeringsijver", pos: "n.m.", cat: "Faith", added: "2026-08-03" },
  { fr: "les obsèques", nl: "de uitvaart, begrafenis", pos: "n.f.pl", cat: "Faith", added: "2026-08-03" },

  // --- Work & study ---
  { fr: "l'entretien d'embauche", nl: "sollicitatiegesprek", pos: "n.m.", cat: "Work", added: "2026-08-03" },
  { fr: "prendre du galon", nl: "promotie maken", pos: "expr", cat: "Work", added: "2026-08-03" },
  { fr: "recalé", nl: "gebuisd, gezakt", pos: "adj", cat: "Work", added: "2026-08-03" },
  { fr: "le manutentionnaire", nl: "magazijnier", pos: "n.m.", cat: "Work", added: "2026-08-03" },
  { fr: "le domaine de prédilection", nl: "voorkeursgebied, specialiteit", pos: "n.m.", cat: "Work", added: "2026-08-03" },
  { fr: "le concessionnaire", nl: "dealer, officiële handelaar", pos: "n.m.", cat: "Work", added: "2026-08-03" },
  { fr: "foncier", nl: "grond-, vastgoed- (bv. taxe foncière)", pos: "adj", cat: "Work", added: "2026-08-29" },
  { fr: "le cordonnier", nl: "de schoenmaker", pos: "n.m.", cat: "Work", added: "2026-08-29" },
  { fr: "le gagne-pain", nl: "kostwinning, broodwinning", pos: "n.m.", cat: "Work", added: "2026-08-29" },
  { fr: "comptabiliser", nl: "registreren, boekhouden", pos: "v", cat: "Work", added: "2026-09-11" },
  { fr: "le contremaître", nl: "ploegbaas", pos: "n.m.", cat: "Work", added: "2026-09-16" },
  { fr: "le grutier", nl: "kraanman", pos: "n.m.", cat: "Work", added: "2026-09-16" },

  { fr: "juteux", nl: "lucratief", pos: "adj", cat: "Work", added: "2026-09-27" },
  { fr: "clore ses affaires", nl: "zijn/hun zaken afsluiten", pos: "expr", cat: "Work", added: "2026-09-27" },
  { fr: "le maraîchage", nl: "groenteteelt", pos: "n.m.", cat: "Work", added: "2026-09-27" },
  // --- Language & reading ---
  { fr: "la maxime", nl: "spreuk, zinspreuk", pos: "n.f.", cat: "Language", added: "2026-08-03" },
  { fr: "la tournure", nl: "formulering, wending", pos: "n.f.", cat: "Language", added: "2026-08-03" },
  { fr: "décortiquer", nl: "ontleden, uitpluizen", pos: "v", cat: "Language", added: "2026-08-03" },
  { fr: "un tuyau miracle", nl: "een wondertip", pos: "n.m.", cat: "Language", added: "2026-08-03" },
  { fr: "l'astuce", nl: "truc, handige tip", pos: "n.f.", cat: "Language", added: "2026-08-03" },
  { fr: "le fascicule", nl: "brochure, katern", pos: "n.m.", cat: "Language", added: "2026-08-03" },
  { fr: "le polar", nl: "misdaadroman, thriller", pos: "n.m.", cat: "Language", added: "2026-08-03" },
  { fr: "effleurer", nl: "een onderwerp aanstippen", pos: "v", cat: "Language", added: "2026-09-11" },

  { fr: "impondérable", nl: "onberekenbaar, onvoorspelbaar", pos: "adj", cat: "Language", added: "2026-09-27" },
  { fr: "limpide", nl: "helder, duidelijk", pos: "adj", cat: "Language", added: "2026-09-27" },
  // --- Food & drink ---
  { fr: "le poivron", nl: "paprika", pos: "n.m.", cat: "Food", added: "2026-08-03" },
  { fr: "la date de péremption", nl: "houdbaarheidsdatum", pos: "n.f.", cat: "Food", added: "2026-08-03" },
  { fr: "comestible", nl: "eetbaar", pos: "adj", cat: "Food", added: "2026-08-03" },
  { fr: "un en-cas", nl: "snack, tussendoortje", pos: "n.m.", cat: "Food", added: "2026-08-03" },
  { fr: "grignoter", nl: "knabbelen", pos: "v", cat: "Food", added: "2026-08-03" },
  { fr: "la galette", nl: "hartige (boekweit)pannenkoek", pos: "n.f.", cat: "Food", added: "2026-08-03" },
  { fr: "gourmand", nl: "gulzig; lekkerbek", pos: "adj", cat: "Food", added: "2026-08-03" },
  { fr: "une cafetière à piston", nl: "cafetière, French press", pos: "n.f.", cat: "Food", added: "2026-08-03" },
  { fr: "trinquer", nl: "proosten, klinken", pos: "v", cat: "Food", added: "2026-08-03" },

  { fr: "de grands millésimes", nl: "topwijnen", pos: "n.m.pl", cat: "Food", added: "2026-09-29" },
  // --- Home & objects ---
  { fr: "un coussin moelleux", nl: "een zacht kussen", pos: "n.m.", cat: "Home", added: "2026-08-03" },
  { fr: "mou", nl: "slap, zacht", pos: "adj", cat: "Home", added: "2026-08-03" },
  { fr: "l'anse", nl: "het oor (van een kop, mand of tas)", pos: "n.f.", cat: "Home", added: "2026-08-03" },
  { fr: "à rayures", nl: "gestreept", pos: "adj", cat: "Home", added: "2026-08-03" },
  { fr: "l'argile", nl: "klei", pos: "n.f.", cat: "Home", added: "2026-08-03" },
  { fr: "une borne", nl: "zuil, terminal, paal", pos: "n.f.", cat: "Home", added: "2026-08-03" },
  { fr: "fripé", nl: "verkreukeld", pos: "adj", cat: "Home", added: "2026-08-03" },
  { fr: "le gabarit", nl: "formaat, afmeting", pos: "n.m.", cat: "Home", added: "2026-08-29" },
  { fr: "épais", nl: "dik", pos: "adj", cat: "Home", added: "2026-08-29" },
  { fr: "indélébile", nl: "onuitwisbaar", pos: "adj", cat: "Home", added: "2026-08-29" },
  { fr: "une rame", nl: "roeiriem, roeispaan", pos: "n.f.", cat: "Home", added: "2026-08-29" },
  { fr: "une bécane", nl: "brommer, motorfiets", pos: "n.f.", cat: "Home", added: "2026-08-29" },
  { fr: "le faisceau", nl: "bundel", pos: "n.m.", cat: "Home", added: "2026-09-11" },
  { fr: "la fourgonnette", nl: "busje", pos: "n.f.", cat: "Home", added: "2026-09-11" },
  { fr: "l'acier", nl: "staal", pos: "n.m.", cat: "Home", added: "2026-09-11" },
  { fr: "le parpaing", nl: "betonblok", pos: "n.m.", cat: "Home", added: "2026-09-11" },
  { fr: "cabossé", nl: "ingedeukt", pos: "adj", cat: "Home", added: "2026-09-11" },
  { fr: "une sangle", nl: "een riem", pos: "n.f.", cat: "Home", added: "2026-09-11" },
  { fr: "le canif", nl: "pennenmes, zakmes", pos: "n.m.", cat: "Home", added: "2026-09-11" },

  // --- Nature & science ---
  { fr: "le poulailler", nl: "kippenhok", pos: "n.m.", cat: "Nature", added: "2026-08-03" },
  { fr: "se désagréger", nl: "uiteenvallen, afbrokkelen", pos: "v", cat: "Nature", added: "2026-08-03" },
  { fr: "l'énergie éolienne", nl: "windenergie", pos: "n.f.", cat: "Nature", added: "2026-08-03" },
  { fr: "nocif", nl: "schadelijk", pos: "adj", cat: "Nature", added: "2026-08-29" },
  { fr: "la pétole", nl: "windstilte, geen zuchtje wind", pos: "n.f.", cat: "Nature", added: "2026-08-29" },
  { fr: "le panache", nl: "pluim (bv. rookpluim)", pos: "n.m.", cat: "Nature", added: "2026-08-29" },
  { fr: "l'écume blanche", nl: "wit schuim", pos: "n.f.", cat: "Nature", added: "2026-08-29" },
  { fr: "la houle", nl: "deining", pos: "n.f.", cat: "Nature", added: "2026-08-29" },
  { fr: "la paroi", nl: "wand (bv. rotswand)", pos: "n.f.", cat: "Nature", added: "2026-08-29" },
  { fr: "déferler", nl: "breken, neerslaan (golven)", pos: "v", cat: "Nature", added: "2026-08-29" },
  { fr: "le récif", nl: "het rif", pos: "n.m.", cat: "Nature", added: "2026-08-29" },
  { fr: "l'affaissement", nl: "verzakking", pos: "n.m.", cat: "Nature", added: "2026-08-29" },
  { fr: "un relevé", nl: "meting, opname", pos: "n.m.", cat: "Nature", added: "2026-08-29" },
  { fr: "la lisière", nl: "rand, zoom (bv. bosrand)", pos: "n.f.", cat: "Nature", added: "2026-08-29" },
  { fr: "les aboiements", nl: "het geblaf", pos: "n.m.pl", cat: "Nature", added: "2026-09-11" },
  { fr: "la période de taille", nl: "snoeiperiode", pos: "n.f.", cat: "Nature", added: "2026-09-11" },
  { fr: "les ronces", nl: "bramen, doornstruiken", pos: "n.f.pl", cat: "Nature", added: "2026-09-11" },
  { fr: "le gravier", nl: "grind", pos: "n.m.", cat: "Nature", added: "2026-09-11" },
  { fr: "la chenille", nl: "rups", pos: "n.f.", cat: "Nature", added: "2026-09-16" },
  { fr: "les griffes", nl: "klauwen", pos: "n.f.pl", cat: "Nature", added: "2026-09-16" },

  // --- Love & relationships ---
  { fr: "avoir qqn dans la peau", nl: "smoorverliefd zijn op iemand", pos: "expr", cat: "Love", added: "2026-09-16" },
  { fr: "bécoter", nl: "zoenen", pos: "v", cat: "Love", added: "2026-09-16" },
  { fr: "elle m'envoûte", nl: "ze brengt mijn hoofd op hol", pos: "expr", cat: "Love", added: "2026-09-16" },
  { fr: "une partouze", nl: "orgie", pos: "n.f.", cat: "Love", added: "2026-09-16" },
];
