// Starter deck of common French words.
// fr: the word as you'd learn it (nouns include their article)
// en: English meaning  |  pos: part of speech  |  cat: category
export const WORDS = [
  // --- Greetings & basics ---
  { fr: "bonjour", en: "hello / good morning", pos: "interj", cat: "Greetings" },
  { fr: "bonsoir", en: "good evening", pos: "interj", cat: "Greetings" },
  { fr: "salut", en: "hi / bye (informal)", pos: "interj", cat: "Greetings" },
  { fr: "au revoir", en: "goodbye", pos: "interj", cat: "Greetings" },
  { fr: "s'il vous plaît", en: "please (formal)", pos: "phrase", cat: "Greetings" },
  { fr: "merci", en: "thank you", pos: "interj", cat: "Greetings" },
  { fr: "de rien", en: "you're welcome", pos: "phrase", cat: "Greetings" },
  { fr: "pardon", en: "sorry / excuse me", pos: "interj", cat: "Greetings" },
  { fr: "excusez-moi", en: "excuse me (formal)", pos: "phrase", cat: "Greetings" },
  { fr: "oui", en: "yes", pos: "adv", cat: "Greetings" },
  { fr: "non", en: "no", pos: "adv", cat: "Greetings" },
  { fr: "peut-être", en: "maybe", pos: "adv", cat: "Greetings" },
  { fr: "d'accord", en: "okay / agreed", pos: "phrase", cat: "Greetings" },
  { fr: "à bientôt", en: "see you soon", pos: "phrase", cat: "Greetings" },
  { fr: "bienvenue", en: "welcome", pos: "interj", cat: "Greetings" },

  // --- Question words ---
  { fr: "qui", en: "who", pos: "pron", cat: "Questions" },
  { fr: "quoi", en: "what", pos: "pron", cat: "Questions" },
  { fr: "où", en: "where", pos: "adv", cat: "Questions" },
  { fr: "quand", en: "when", pos: "adv", cat: "Questions" },
  { fr: "pourquoi", en: "why", pos: "adv", cat: "Questions" },
  { fr: "comment", en: "how", pos: "adv", cat: "Questions" },
  { fr: "combien", en: "how much / how many", pos: "adv", cat: "Questions" },
  { fr: "quel", en: "which / what", pos: "adj", cat: "Questions" },

  // --- People & family ---
  { fr: "l'homme", en: "the man", pos: "n.m.", cat: "People" },
  { fr: "la femme", en: "the woman / the wife", pos: "n.f.", cat: "People" },
  { fr: "l'enfant", en: "the child", pos: "n.m.", cat: "People" },
  { fr: "le garçon", en: "the boy", pos: "n.m.", cat: "People" },
  { fr: "la fille", en: "the girl / the daughter", pos: "n.f.", cat: "People" },
  { fr: "le père", en: "the father", pos: "n.m.", cat: "People" },
  { fr: "la mère", en: "the mother", pos: "n.f.", cat: "People" },
  { fr: "le fils", en: "the son", pos: "n.m.", cat: "People" },
  { fr: "le frère", en: "the brother", pos: "n.m.", cat: "People" },
  { fr: "la sœur", en: "the sister", pos: "n.f.", cat: "People" },
  { fr: "les parents", en: "the parents", pos: "n.m.pl", cat: "People" },
  { fr: "l'ami", en: "the friend", pos: "n.m.", cat: "People" },
  { fr: "le voisin", en: "the neighbour", pos: "n.m.", cat: "People" },
  { fr: "les gens", en: "people", pos: "n.m.pl", cat: "People" },
  { fr: "le monde", en: "the world / everyone", pos: "n.m.", cat: "People" },

  // --- Food & drink ---
  { fr: "le pain", en: "the bread", pos: "n.m.", cat: "Food" },
  { fr: "le fromage", en: "the cheese", pos: "n.m.", cat: "Food" },
  { fr: "le beurre", en: "the butter", pos: "n.m.", cat: "Food" },
  { fr: "l'œuf", en: "the egg", pos: "n.m.", cat: "Food" },
  { fr: "la viande", en: "the meat", pos: "n.f.", cat: "Food" },
  { fr: "le poisson", en: "the fish", pos: "n.m.", cat: "Food" },
  { fr: "le poulet", en: "the chicken", pos: "n.m.", cat: "Food" },
  { fr: "le légume", en: "the vegetable", pos: "n.m.", cat: "Food" },
  { fr: "le fruit", en: "the fruit", pos: "n.m.", cat: "Food" },
  { fr: "la pomme", en: "the apple", pos: "n.f.", cat: "Food" },
  { fr: "la pomme de terre", en: "the potato", pos: "n.f.", cat: "Food" },
  { fr: "le riz", en: "the rice", pos: "n.m.", cat: "Food" },
  { fr: "le sucre", en: "the sugar", pos: "n.m.", cat: "Food" },
  { fr: "le sel", en: "the salt", pos: "n.m.", cat: "Food" },
  { fr: "l'eau", en: "the water", pos: "n.f.", cat: "Food" },
  { fr: "le vin", en: "the wine", pos: "n.m.", cat: "Food" },
  { fr: "la bière", en: "the beer", pos: "n.f.", cat: "Food" },
  { fr: "le café", en: "the coffee / the café", pos: "n.m.", cat: "Food" },
  { fr: "le lait", en: "the milk", pos: "n.m.", cat: "Food" },
  { fr: "le repas", en: "the meal", pos: "n.m.", cat: "Food" },
  { fr: "le petit déjeuner", en: "the breakfast", pos: "n.m.", cat: "Food" },
  { fr: "le déjeuner", en: "the lunch", pos: "n.m.", cat: "Food" },
  { fr: "le dîner", en: "the dinner", pos: "n.m.", cat: "Food" },
  { fr: "l'addition", en: "the bill / the check", pos: "n.f.", cat: "Food" },

  // --- Home & objects ---
  { fr: "la maison", en: "the house", pos: "n.f.", cat: "Home" },
  { fr: "l'appartement", en: "the flat / the apartment", pos: "n.m.", cat: "Home" },
  { fr: "la chambre", en: "the bedroom", pos: "n.f.", cat: "Home" },
  { fr: "la cuisine", en: "the kitchen / the cooking", pos: "n.f.", cat: "Home" },
  { fr: "la salle de bains", en: "the bathroom", pos: "n.f.", cat: "Home" },
  { fr: "la porte", en: "the door", pos: "n.f.", cat: "Home" },
  { fr: "la fenêtre", en: "the window", pos: "n.f.", cat: "Home" },
  { fr: "la table", en: "the table", pos: "n.f.", cat: "Home" },
  { fr: "la chaise", en: "the chair", pos: "n.f.", cat: "Home" },
  { fr: "le lit", en: "the bed", pos: "n.m.", cat: "Home" },
  { fr: "la clé", en: "the key", pos: "n.f.", cat: "Home" },
  { fr: "le livre", en: "the book", pos: "n.m.", cat: "Home" },
  { fr: "le téléphone", en: "the phone", pos: "n.m.", cat: "Home" },
  { fr: "l'argent", en: "the money / silver", pos: "n.m.", cat: "Home" },
  { fr: "le sac", en: "the bag", pos: "n.m.", cat: "Home" },

  // --- Travel & places ---
  { fr: "la ville", en: "the city / the town", pos: "n.f.", cat: "Travel" },
  { fr: "le pays", en: "the country", pos: "n.m.", cat: "Travel" },
  { fr: "la rue", en: "the street", pos: "n.f.", cat: "Travel" },
  { fr: "la route", en: "the road", pos: "n.f.", cat: "Travel" },
  { fr: "la gare", en: "the train station", pos: "n.f.", cat: "Travel" },
  { fr: "l'aéroport", en: "the airport", pos: "n.m.", cat: "Travel" },
  { fr: "le train", en: "the train", pos: "n.m.", cat: "Travel" },
  { fr: "la voiture", en: "the car", pos: "n.f.", cat: "Travel" },
  { fr: "l'avion", en: "the plane", pos: "n.m.", cat: "Travel" },
  { fr: "le vélo", en: "the bicycle", pos: "n.m.", cat: "Travel" },
  { fr: "le voyage", en: "the trip / the journey", pos: "n.m.", cat: "Travel" },
  { fr: "l'hôtel", en: "the hotel", pos: "n.m.", cat: "Travel" },
  { fr: "le magasin", en: "the shop", pos: "n.m.", cat: "Travel" },
  { fr: "le marché", en: "the market", pos: "n.m.", cat: "Travel" },
  { fr: "la plage", en: "the beach", pos: "n.f.", cat: "Travel" },
  { fr: "le billet", en: "the ticket", pos: "n.m.", cat: "Travel" },
  { fr: "à gauche", en: "on the left", pos: "phrase", cat: "Travel" },
  { fr: "à droite", en: "on the right", pos: "phrase", cat: "Travel" },
  { fr: "tout droit", en: "straight ahead", pos: "phrase", cat: "Travel" },

  // --- Time ---
  { fr: "le jour", en: "the day", pos: "n.m.", cat: "Time" },
  { fr: "la nuit", en: "the night", pos: "n.f.", cat: "Time" },
  { fr: "le matin", en: "the morning", pos: "n.m.", cat: "Time" },
  { fr: "l'après-midi", en: "the afternoon", pos: "n.m.", cat: "Time" },
  { fr: "le soir", en: "the evening", pos: "n.m.", cat: "Time" },
  { fr: "la semaine", en: "the week", pos: "n.f.", cat: "Time" },
  { fr: "le mois", en: "the month", pos: "n.m.", cat: "Time" },
  { fr: "l'année", en: "the year", pos: "n.f.", cat: "Time" },
  { fr: "l'heure", en: "the hour / the time", pos: "n.f.", cat: "Time" },
  { fr: "aujourd'hui", en: "today", pos: "adv", cat: "Time" },
  { fr: "demain", en: "tomorrow", pos: "adv", cat: "Time" },
  { fr: "hier", en: "yesterday", pos: "adv", cat: "Time" },
  { fr: "maintenant", en: "now", pos: "adv", cat: "Time" },
  { fr: "toujours", en: "always / still", pos: "adv", cat: "Time" },
  { fr: "jamais", en: "never", pos: "adv", cat: "Time" },
  { fr: "souvent", en: "often", pos: "adv", cat: "Time" },
  { fr: "parfois", en: "sometimes", pos: "adv", cat: "Time" },
  { fr: "bientôt", en: "soon", pos: "adv", cat: "Time" },
  { fr: "déjà", en: "already", pos: "adv", cat: "Time" },
  { fr: "encore", en: "again / still", pos: "adv", cat: "Time" },
  { fr: "lundi", en: "Monday", pos: "n.m.", cat: "Time" },
  { fr: "mardi", en: "Tuesday", pos: "n.m.", cat: "Time" },
  { fr: "mercredi", en: "Wednesday", pos: "n.m.", cat: "Time" },
  { fr: "jeudi", en: "Thursday", pos: "n.m.", cat: "Time" },
  { fr: "vendredi", en: "Friday", pos: "n.m.", cat: "Time" },
  { fr: "samedi", en: "Saturday", pos: "n.m.", cat: "Time" },
  { fr: "dimanche", en: "Sunday", pos: "n.m.", cat: "Time" },

  // --- Numbers ---
  { fr: "un", en: "one", pos: "num", cat: "Numbers" },
  { fr: "deux", en: "two", pos: "num", cat: "Numbers" },
  { fr: "trois", en: "three", pos: "num", cat: "Numbers" },
  { fr: "quatre", en: "four", pos: "num", cat: "Numbers" },
  { fr: "cinq", en: "five", pos: "num", cat: "Numbers" },
  { fr: "six", en: "six", pos: "num", cat: "Numbers" },
  { fr: "sept", en: "seven", pos: "num", cat: "Numbers" },
  { fr: "huit", en: "eight", pos: "num", cat: "Numbers" },
  { fr: "neuf", en: "nine", pos: "num", cat: "Numbers" },
  { fr: "dix", en: "ten", pos: "num", cat: "Numbers" },
  { fr: "vingt", en: "twenty", pos: "num", cat: "Numbers" },
  { fr: "trente", en: "thirty", pos: "num", cat: "Numbers" },
  { fr: "cinquante", en: "fifty", pos: "num", cat: "Numbers" },
  { fr: "cent", en: "hundred", pos: "num", cat: "Numbers" },
  { fr: "mille", en: "thousand", pos: "num", cat: "Numbers" },
  { fr: "premier", en: "first", pos: "adj", cat: "Numbers" },
  { fr: "dernier", en: "last", pos: "adj", cat: "Numbers" },

  // --- Verbs ---
  { fr: "être", en: "to be", pos: "v", cat: "Verbs" },
  { fr: "avoir", en: "to have", pos: "v", cat: "Verbs" },
  { fr: "faire", en: "to do / to make", pos: "v", cat: "Verbs" },
  { fr: "aller", en: "to go", pos: "v", cat: "Verbs" },
  { fr: "venir", en: "to come", pos: "v", cat: "Verbs" },
  { fr: "dire", en: "to say", pos: "v", cat: "Verbs" },
  { fr: "voir", en: "to see", pos: "v", cat: "Verbs" },
  { fr: "savoir", en: "to know (a fact)", pos: "v", cat: "Verbs" },
  { fr: "connaître", en: "to know (a person/place)", pos: "v", cat: "Verbs" },
  { fr: "pouvoir", en: "to be able to / can", pos: "v", cat: "Verbs" },
  { fr: "vouloir", en: "to want", pos: "v", cat: "Verbs" },
  { fr: "devoir", en: "to have to / must", pos: "v", cat: "Verbs" },
  { fr: "prendre", en: "to take", pos: "v", cat: "Verbs" },
  { fr: "mettre", en: "to put", pos: "v", cat: "Verbs" },
  { fr: "donner", en: "to give", pos: "v", cat: "Verbs" },
  { fr: "parler", en: "to speak", pos: "v", cat: "Verbs" },
  { fr: "demander", en: "to ask", pos: "v", cat: "Verbs" },
  { fr: "répondre", en: "to answer", pos: "v", cat: "Verbs" },
  { fr: "penser", en: "to think", pos: "v", cat: "Verbs" },
  { fr: "croire", en: "to believe", pos: "v", cat: "Verbs" },
  { fr: "aimer", en: "to like / to love", pos: "v", cat: "Verbs" },
  { fr: "manger", en: "to eat", pos: "v", cat: "Verbs" },
  { fr: "boire", en: "to drink", pos: "v", cat: "Verbs" },
  { fr: "dormir", en: "to sleep", pos: "v", cat: "Verbs" },
  { fr: "lire", en: "to read", pos: "v", cat: "Verbs" },
  { fr: "écrire", en: "to write", pos: "v", cat: "Verbs" },
  { fr: "écouter", en: "to listen", pos: "v", cat: "Verbs" },
  { fr: "entendre", en: "to hear", pos: "v", cat: "Verbs" },
  { fr: "regarder", en: "to watch / to look at", pos: "v", cat: "Verbs" },
  { fr: "attendre", en: "to wait for", pos: "v", cat: "Verbs" },
  { fr: "acheter", en: "to buy", pos: "v", cat: "Verbs" },
  { fr: "payer", en: "to pay", pos: "v", cat: "Verbs" },
  { fr: "travailler", en: "to work", pos: "v", cat: "Verbs" },
  { fr: "habiter", en: "to live (somewhere)", pos: "v", cat: "Verbs" },
  { fr: "marcher", en: "to walk / to work (function)", pos: "v", cat: "Verbs" },
  { fr: "courir", en: "to run", pos: "v", cat: "Verbs" },
  { fr: "partir", en: "to leave", pos: "v", cat: "Verbs" },
  { fr: "arriver", en: "to arrive / to happen", pos: "v", cat: "Verbs" },
  { fr: "rester", en: "to stay", pos: "v", cat: "Verbs" },
  { fr: "trouver", en: "to find", pos: "v", cat: "Verbs" },
  { fr: "chercher", en: "to look for", pos: "v", cat: "Verbs" },
  { fr: "ouvrir", en: "to open", pos: "v", cat: "Verbs" },
  { fr: "fermer", en: "to close", pos: "v", cat: "Verbs" },
  { fr: "commencer", en: "to begin", pos: "v", cat: "Verbs" },
  { fr: "finir", en: "to finish", pos: "v", cat: "Verbs" },
  { fr: "apprendre", en: "to learn", pos: "v", cat: "Verbs" },
  { fr: "comprendre", en: "to understand", pos: "v", cat: "Verbs" },
  { fr: "oublier", en: "to forget", pos: "v", cat: "Verbs" },
  { fr: "se souvenir", en: "to remember", pos: "v", cat: "Verbs" },
  { fr: "jouer", en: "to play", pos: "v", cat: "Verbs" },

  // --- Adjectives ---
  { fr: "grand", en: "big / tall", pos: "adj", cat: "Adjectives" },
  { fr: "petit", en: "small", pos: "adj", cat: "Adjectives" },
  { fr: "bon", en: "good", pos: "adj", cat: "Adjectives" },
  { fr: "mauvais", en: "bad", pos: "adj", cat: "Adjectives" },
  { fr: "beau", en: "beautiful / handsome", pos: "adj", cat: "Adjectives" },
  { fr: "joli", en: "pretty", pos: "adj", cat: "Adjectives" },
  { fr: "nouveau", en: "new", pos: "adj", cat: "Adjectives" },
  { fr: "vieux", en: "old", pos: "adj", cat: "Adjectives" },
  { fr: "jeune", en: "young", pos: "adj", cat: "Adjectives" },
  { fr: "long", en: "long", pos: "adj", cat: "Adjectives" },
  { fr: "court", en: "short", pos: "adj", cat: "Adjectives" },
  { fr: "chaud", en: "hot / warm", pos: "adj", cat: "Adjectives" },
  { fr: "froid", en: "cold", pos: "adj", cat: "Adjectives" },
  { fr: "facile", en: "easy", pos: "adj", cat: "Adjectives" },
  { fr: "difficile", en: "difficult", pos: "adj", cat: "Adjectives" },
  { fr: "cher", en: "expensive / dear", pos: "adj", cat: "Adjectives" },
  { fr: "content", en: "happy / pleased", pos: "adj", cat: "Adjectives" },
  { fr: "triste", en: "sad", pos: "adj", cat: "Adjectives" },
  { fr: "fatigué", en: "tired", pos: "adj", cat: "Adjectives" },
  { fr: "malade", en: "sick", pos: "adj", cat: "Adjectives" },
  { fr: "prêt", en: "ready", pos: "adj", cat: "Adjectives" },
  { fr: "plein", en: "full", pos: "adj", cat: "Adjectives" },
  { fr: "vide", en: "empty", pos: "adj", cat: "Adjectives" },
  { fr: "propre", en: "clean / own", pos: "adj", cat: "Adjectives" },
  { fr: "sale", en: "dirty", pos: "adj", cat: "Adjectives" },
  { fr: "lent", en: "slow", pos: "adj", cat: "Adjectives" },
  { fr: "rapide", en: "fast", pos: "adj", cat: "Adjectives" },
  { fr: "fort", en: "strong / loud", pos: "adj", cat: "Adjectives" },
  { fr: "gratuit", en: "free (no cost)", pos: "adj", cat: "Adjectives" },

  // --- Colours ---
  { fr: "rouge", en: "red", pos: "adj", cat: "Colours" },
  { fr: "bleu", en: "blue", pos: "adj", cat: "Colours" },
  { fr: "vert", en: "green", pos: "adj", cat: "Colours" },
  { fr: "jaune", en: "yellow", pos: "adj", cat: "Colours" },
  { fr: "noir", en: "black", pos: "adj", cat: "Colours" },
  { fr: "blanc", en: "white", pos: "adj", cat: "Colours" },
  { fr: "gris", en: "grey", pos: "adj", cat: "Colours" },
  { fr: "brun", en: "brown", pos: "adj", cat: "Colours" },
  { fr: "orange", en: "orange", pos: "adj", cat: "Colours" },
  { fr: "rose", en: "pink", pos: "adj", cat: "Colours" },

  // --- Body & health ---
  { fr: "la tête", en: "the head", pos: "n.f.", cat: "Body" },
  { fr: "la main", en: "the hand", pos: "n.f.", cat: "Body" },
  { fr: "le pied", en: "the foot", pos: "n.m.", cat: "Body" },
  { fr: "l'œil", en: "the eye", pos: "n.m.", cat: "Body" },
  { fr: "les yeux", en: "the eyes", pos: "n.m.pl", cat: "Body" },
  { fr: "la bouche", en: "the mouth", pos: "n.f.", cat: "Body" },
  { fr: "le cœur", en: "the heart", pos: "n.m.", cat: "Body" },
  { fr: "le bras", en: "the arm", pos: "n.m.", cat: "Body" },
  { fr: "la jambe", en: "the leg", pos: "n.f.", cat: "Body" },
  { fr: "le médecin", en: "the doctor", pos: "n.m.", cat: "Body" },
  { fr: "la douleur", en: "the pain", pos: "n.f.", cat: "Body" },

  // --- Work & school ---
  { fr: "le travail", en: "the work / the job", pos: "n.m.", cat: "Work" },
  { fr: "le bureau", en: "the office / the desk", pos: "n.m.", cat: "Work" },
  { fr: "l'école", en: "the school", pos: "n.f.", cat: "Work" },
  { fr: "le professeur", en: "the teacher", pos: "n.m.", cat: "Work" },
  { fr: "l'élève", en: "the pupil", pos: "n.m.", cat: "Work" },
  { fr: "le cours", en: "the class / the course", pos: "n.m.", cat: "Work" },
  { fr: "la question", en: "the question", pos: "n.f.", cat: "Work" },
  { fr: "la réponse", en: "the answer", pos: "n.f.", cat: "Work" },
  { fr: "le mot", en: "the word", pos: "n.m.", cat: "Work" },
  { fr: "la langue", en: "the language / the tongue", pos: "n.f.", cat: "Work" },
  { fr: "l'entreprise", en: "the company", pos: "n.f.", cat: "Work" },
  { fr: "la réunion", en: "the meeting", pos: "n.f.", cat: "Work" },

  // --- Nature & weather ---
  { fr: "le soleil", en: "the sun", pos: "n.m.", cat: "Nature" },
  { fr: "la pluie", en: "the rain", pos: "n.f.", cat: "Nature" },
  { fr: "la neige", en: "the snow", pos: "n.f.", cat: "Nature" },
  { fr: "le vent", en: "the wind", pos: "n.m.", cat: "Nature" },
  { fr: "le ciel", en: "the sky", pos: "n.m.", cat: "Nature" },
  { fr: "la mer", en: "the sea", pos: "n.f.", cat: "Nature" },
  { fr: "la montagne", en: "the mountain", pos: "n.f.", cat: "Nature" },
  { fr: "l'arbre", en: "the tree", pos: "n.m.", cat: "Nature" },
  { fr: "la fleur", en: "the flower", pos: "n.f.", cat: "Nature" },
  { fr: "le chien", en: "the dog", pos: "n.m.", cat: "Nature" },
  { fr: "le chat", en: "the cat", pos: "n.m.", cat: "Nature" },
  { fr: "l'oiseau", en: "the bird", pos: "n.m.", cat: "Nature" },
  { fr: "le temps", en: "the weather / the time", pos: "n.m.", cat: "Nature" },

  // --- Small connecting words ---
  { fr: "et", en: "and", pos: "conj", cat: "Connectors" },
  { fr: "mais", en: "but", pos: "conj", cat: "Connectors" },
  { fr: "ou", en: "or", pos: "conj", cat: "Connectors" },
  { fr: "parce que", en: "because", pos: "conj", cat: "Connectors" },
  { fr: "donc", en: "so / therefore", pos: "conj", cat: "Connectors" },
  { fr: "avec", en: "with", pos: "prep", cat: "Connectors" },
  { fr: "sans", en: "without", pos: "prep", cat: "Connectors" },
  { fr: "pour", en: "for / in order to", pos: "prep", cat: "Connectors" },
  { fr: "chez", en: "at the home of", pos: "prep", cat: "Connectors" },
  { fr: "entre", en: "between", pos: "prep", cat: "Connectors" },
  { fr: "sous", en: "under", pos: "prep", cat: "Connectors" },
  { fr: "sur", en: "on", pos: "prep", cat: "Connectors" },
  { fr: "devant", en: "in front of", pos: "prep", cat: "Connectors" },
  { fr: "derrière", en: "behind", pos: "prep", cat: "Connectors" },
  { fr: "pendant", en: "during", pos: "prep", cat: "Connectors" },
  { fr: "beaucoup", en: "a lot / many", pos: "adv", cat: "Connectors" },
  { fr: "un peu", en: "a little", pos: "adv", cat: "Connectors" },
  { fr: "trop", en: "too much", pos: "adv", cat: "Connectors" },
  { fr: "assez", en: "enough / quite", pos: "adv", cat: "Connectors" },
  { fr: "très", en: "very", pos: "adv", cat: "Connectors" },
  { fr: "aussi", en: "also / too", pos: "adv", cat: "Connectors" },
  { fr: "presque", en: "almost", pos: "adv", cat: "Connectors" },
  { fr: "vraiment", en: "really", pos: "adv", cat: "Connectors" },
];
